meta_product_name: "HandyBee"
meta_title: "HandyBee - Fix your house in a few clicks"
meta_description: "Book your next handy person appointment now"
meta_image: "bee.png" # should exist in `app/assets/images/`
